# Makefile
TOP = ../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

RESTORES += example.cwConfig

include $(TOP)/configure/RULES
include $(TOP)/configure/RULES.Restore
#----------------------------------------
#  ADD RULES AFTER THIS LINE
