#This Makefile created by makeMakefile.pl


all :
	$(MAKE) -f ../Makefile TOP=../../.. T_A=linuxRT_glibc-i686  $@

.DEFAULT: force
	$(MAKE) -f ../Makefile TOP=../../.. T_A=linuxRT_glibc-i686  $@

force:  ;
