#This Makefile created by makeMakefile.pl


all :
	$(MAKE) -f ../Makefile TOP=../../.. T_A=linuxRT_glibc-x86_64  $@

.DEFAULT: force
	$(MAKE) -f ../Makefile TOP=../../.. T_A=linuxRT_glibc-x86_64  $@

force:  ;
